name: advNlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.6=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.5=h37ad1db_4
  - aws-c-cal=0.6.9=h3b91eb8_1
  - aws-c-common=0.9.8=hd590300_0
  - aws-c-compression=0.2.17=hfd9eb17_6
  - aws-c-event-stream=0.3.2=hae413d4_6
  - aws-c-http=0.7.14=h162056d_1
  - aws-c-io=0.13.35=hc23c90e_8
  - aws-c-mqtt=0.9.9=h1387108_0
  - aws-c-s3=0.3.22=h40300e3_3
  - aws-c-sdkutils=0.1.12=hfd9eb17_5
  - aws-checksums=0.1.17=hfd9eb17_5
  - aws-crt-cpp=0.24.5=h20be23b_3
  - aws-sdk-cpp=1.11.182=h8df25a1_5
  - binaryornot=0.4.4=py_1
  - blas=1.0=mkl
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.21.0=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - cffi=1.16.0=py310h2fee648_0
  - chardet=5.2.0=py310hff52083_1
  - click=8.1.7=unix_pyh707e725_0
  - conda=23.10.0=py310hff52083_1
  - contourpy=1.2.0=py310hd41b1e2_0
  - cookiecutter=2.4.0=pyhca7485f_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.14.6=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - evaluate=0.4.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.9.0=py310h06a4308_0
  - fmt=10.1.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.44.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.0=py310h2372a71_1
  - fsspec=2023.10.0=pyhca7485f_0
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glib=2.78.1=hfc55251_0
  - glib-tools=2.78.1=hfc55251_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.6=h8e1006c_2
  - gstreamer=1.22.6=h98fc4e7_2
  - harfbuzz=8.2.1=h3d44ed6_0
  - huggingface_hub=0.17.3=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hb7c19ff_3
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarchive=3.7.2=h039dbb9_0
  - libarrow=14.0.1=h0406937_1_cpu
  - libarrow-acero=14.0.1=h59595ed_1_cpu
  - libarrow-dataset=14.0.1=h59595ed_1_cpu
  - libarrow-flight=14.0.1=h120cb0d_1_cpu
  - libarrow-flight-sql=14.0.1=h61ff412_1_cpu
  - libarrow-gandiva=14.0.1=hacb8726_1_cpu
  - libarrow-substrait=14.0.1=h61ff412_1_cpu
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.0.34=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.4.52=0
  - libcurl=8.4.0=hca28451_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgcrypt=1.10.2=hd590300_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.59.2=hd6c4280_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - libllvm15=15.0.7=h5cf9203_3
  - libmamba=1.5.3=had39da4_2
  - libmambapy=1.5.3=py310h39ff949_2
  - libnghttp2=1.58.0=h47da74e_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libparquet=14.0.1=h352af49_1_cpu
  - libpng=1.6.39=h753d276_0
  - libpq=16.1=hfc447b1_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.06.02=h7a70373_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsolv=0.7.26=hfc55251_0
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libsystemd0=254=h3516f8a_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=ha9c0a0a_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.6.0=h5d7e998_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.5.3=py310h51d5547_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.8.1=py310hff52083_0
  - matplotlib-base=3.8.1=py310h62c0568_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.3=h59595ed_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.0.4=py310h2372a71_1
  - multiprocess=0.70.15=py310h2372a71_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h59595ed_2
  - networkx=3.1=py310h06a4308_0
  - nspr=4.35=h27087fc_0
  - nss=3.94=h1d7d5a4_0
  - numpy=1.24.3=py310hd5efca6_0
  - numpy-base=1.24.3=py310h8e6c178_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.1.4=hd590300_0
  - orc=1.9.0=h4b38347_4
  - pandas=2.1.3=py310hcc13569_0
  - pathtools=0.1.2=py_1
  - pcre2=10.40=hc3806b6_0
  - pillow=10.1.0=py310h01dd4db_0
  - pixman=0.42.2=h59595ed_0
  - ply=3.11=py_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - protobuf=4.24.4=py310h620c231_0
  - psutil=5.9.5=py310h2372a71_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_5
  - pyarrow=14.0.1=py310hf9e7431_1_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h2372a71_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py310h2372a71_0
  - python_abi=3.10=4_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - qt-main=5.15.8=h82b777d_17
  - rdma-core=28.9=h59595ed_1
  - re2=2023.06.02=h2873b5e_0
  - readline=8.2=h8228510_1
  - regex=2023.10.3=py310h2372a71_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - responses=0.18.0=pyhd8ed1ab_0
  - rich=13.6.0=pyhd8ed1ab_0
  - ruamel.yaml=0.18.5=py310h2372a71_0
  - ruamel.yaml.clib=0.2.7=py310h2372a71_2
  - s2n=1.3.56=h06160fa_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.3.3=py310hcb5633a_1
  - scikit-learn=1.3.0=py310h1128e8f_0
  - scipy=1.10.1=py310hd5efca6_0
  - sentry-sdk=1.34.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py310h2372a71_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sympy=1.11.1=py310h06a4308_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.14.1=py310h320607d_2
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.0.2=py310_cu118
  - torchtriton=2.0.0=py310
  - tornado=6.3.3=py310h2372a71_1
  - transformers=4.35.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.15.0=h64cca9d_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.40=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - yarl=1.9.2=py310h2372a71_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - accelerate==0.24.1
      - archspec==0.2.2
      - bitsandbytes==0.41.2.post2
      - boltons==23.0.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - conda-libmamba-solver==23.11.0
      - conda-package-handling==2.2.0
      - conda-package-streaming==0.9.0
      - idna==3.4
      - jsonpatch==1.33
      - packaging==23.2
      - peft==0.6.1
      - pip==23.3.1
      - pluggy==1.3.0
      - pycparser==2.21
      - pysocks==1.7.1
      - requests==2.31.0
      - setuptools==68.2.2
      - tqdm==4.66.1
      - truststore==0.8.0
      - urllib3==2.0.7
      - wheel==0.41.3
